### ISSUE TITLE
Url typo

### ISSUE THREAD

**Issue by Cightline** [wltechblog/thingino-installers#6]
First off, thanks for putting together this installer, you saved me a lot of time. 

The url on the Wyze cam 3 README is: https://github.com/themactep/thingino-firmware/releases/tag/firmware 

it should be this: https://github.com/themactep/thingino-firmware/releases

**Comment by wltechblog** [comment]
Good catch. The firmware URL actually changed a few days ago to this new one!

**Comment by wltechblog** [comment]
Closing as solved
